# Generated by Django 6.0 on 2026-02-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreventionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("AVOID_ZONE", "Éviter une zone"),
                            ("WEAR_MASK", "Porter un masque"),
                            ("CHECK_SPO2", "Vérifier SpO₂"),
                            ("CONSULT_DOCTOR", "Consulter un médecin"),
                            ("STAY_HOME", "Rester à domicile"),
                            ("HYDRATE", "S'hydrater"),
                            ("REST", "Se reposer"),
                            ("MONITOR_SYMPTOMS", "Surveiller les symptômes"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "recommendation_text",
                    models.TextField(verbose_name="Texte de recommandation"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "Haute"),
                            ("MEDIUM", "Moyenne"),
                            ("LOW", "Basse"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Complétée"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de complétion"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prevention_actions",
                        to="alerts.alert",
                        verbose_name="Alerte associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action préventive",
                "verbose_name_plural": "Actions préventives",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
