# Generated by Django 6.0 on 2026-02-26 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("treatments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preventionaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prevention_actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="preventionaction",
            index=models.Index(
                fields=["user", "completed"], name="treatments__user_id_36663f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preventionaction",
            index=models.Index(
                fields=["alert", "completed"], name="treatments__alert_i_97cc7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preventionaction",
            index=models.Index(
                fields=["priority", "completed"], name="treatments__priorit_af02fb_idx"
            ),
        ),
    ]
