# Generated by Django 6.0 on 2026-01-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location_lat", models.FloatField()),
                ("location_lon", models.FloatField()),
                ("alert_count", models.IntegerField(default=0)),
                ("avg_pollution", models.FloatField(default=0.0)),
            ],
        ),
    ]
