# Generated by Django 6.0 on 2026-01-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="environment",
            unique_together={("location_lat", "location_lon")},
        ),
        migrations.RemoveField(
            model_name="environment",
            name="name",
        ),
    ]
