# Generated by Django 6.0 on 2026-01-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0002_alter_environment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="environment",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="environment",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
