# Generated by Django 6.0 on 2026-02-26 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("telemedicine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Expéditeur",
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_threads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Médecin",
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_threads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="telemedicine.thread",
                verbose_name="Thread",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="thread",
            unique_together={("patient", "doctor")},
        ),
    ]
