# Generated by Django 6.0 on 2026-01-12 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude GPS (entre -90 et 90)', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude GPS (entre -180 et 180)', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('pm25', models.FloatField(blank=True, help_text='Concentration de particules fines PM2.5 (µg/m³)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PM2.5')),
                ('pm10', models.FloatField(blank=True, help_text='Concentration de particules fines PM10 (µg/m³)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='PM10')),
                ('no2', models.FloatField(blank=True, help_text="Concentration de dioxyde d'azote (µg/m³)", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='NO₂')),
                ('humidity', models.FloatField(blank=True, help_text='Humidité relative (%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Humidité')),
                ('temperature', models.FloatField(blank=True, help_text="Température de l'air (°C)", null=True, verbose_name='Température')),
                ('source', models.CharField(choices=[('IOT_SENSOR', 'Capteur IoT'), ('API_EXTERNE', 'API Externe'), ('MANUAL', 'Saisie manuelle'), ('STATION_FIXE', 'Station de mesure fixe')], default='IOT_SENSOR', max_length=20, verbose_name='Source des données')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la mesure', verbose_name='Horodatage')),
            ],
            options={
                'verbose_name': 'Donnée environnementale',
                'verbose_name_plural': 'Données environnementales',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='environment_timesta_2fd5a2_idx'), models.Index(fields=['latitude', 'longitude'], name='environment_latitud_80db86_idx')],
            },
        ),
    ]
