# Generated by Django 6.0.1 on 2026-01-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("PHASE_1", "Phase 1"),
                            ("PHASE_2", "Phase 2"),
                            ("PHASE_3", "Phase 3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("phase_1_started_at", models.DateTimeField()),
                ("phase_2_started_at", models.DateTimeField(blank=True, null=True)),
                ("phase_3_started_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
