# Generated by Django 6.0.1 on 2026-01-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sensors.sensor"
            ),
        ),
    ]
