# Generated by Django 6.0 on 2026-01-04 03:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
        ("sensors", "0004_alter_environmentalmeasurement_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={},
        ),
        migrations.RemoveField(
            model_name="alert",
            name="user_responded",
        ),
        migrations.AddField(
            model_name="alert",
            name="advice",
            field=models.TextField(default="hk"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alert",
            name="category",
            field=models.CharField(default="Bien", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alert",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="last_iqa_above_threshold_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="started_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="alert",
            name="location_lat",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="alert",
            name="location_lon",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="alert",
            name="sensor_measurement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="sensors.environmentalmeasurement",
            ),
        ),
    ]
