# Generated by Django 6.0 on 2026-01-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_alter_alert_options_remove_alert_user_responded_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alert",
            old_name="started_at",
            new_name="phase_1_started_at",
        ),
        migrations.RenameField(
            model_name="alert",
            old_name="last_iqa_above_threshold_at",
            new_name="phase_2_started_at",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="advice",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="category",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="location_lat",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="location_lon",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="pollution_index",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="sensor_measurement",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="user",
        ),
        migrations.AddField(
            model_name="alert",
            name="phase_3_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
