# Generated by Django 6.0 on 2026-01-10 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_rename_started_at_alert_phase_1_started_at_and_more"),
        ("sensors", "0005_sensor_zone_airqualitymeasurement_sensor_zone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="sensor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sensors.sensor",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="alert",
            name="phase",
            field=models.CharField(
                choices=[
                    ("PHASE_1", "Phase 1"),
                    ("PHASE_2", "Phase 2"),
                    ("PHASE_3", "Phase 3"),
                ],
                max_length=10,
            ),
        ),
    ]
