# Generated by Django 6.0 on 2026-01-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_alert_sensor_alter_alert_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="phase_1_started_at",
            field=models.DateTimeField(),
        ),
    ]
