# Generated by Django 6.0 on 2026-02-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MODERATE", "Modéré"),
                            ("HIGH", "Élevé"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="LOW",
                        max_length=20,
                        verbose_name="Niveau de risque",
                    ),
                ),
                (
                    "pollution_level",
                    models.FloatField(
                        default=0.0,
                        help_text="Niveau de pollution moyen (IQA)",
                        verbose_name="Niveau de pollution",
                    ),
                ),
                (
                    "respiratory_signal_count",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre de signaux respiratoires détectés dans cette zone",
                        verbose_name="Nombre de signaux respiratoires",
                    ),
                ),
                (
                    "high_risk_predictions_count",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre de prédictions à risque élevé dans cette zone",
                        verbose_name="Prédictions à risque élevé",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Zone active"),
                ),
                (
                    "radius_meters",
                    models.FloatField(
                        default=1000.0,
                        help_text="Rayon de la zone en mètres (par défaut 1km)",
                        verbose_name="Rayon (m)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone à risque",
                "verbose_name_plural": "Zones à risque",
                "ordering": ["-risk_level", "-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="HealthFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nom de l'établissement"
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("HOSPITAL", "Hôpital Général"),
                            ("PNEUMOLOGY_CENTER", "Centre de Pneumologie"),
                            ("CLINIC", "Clinique"),
                            ("HEALTH_CENTER", "Centre de Santé"),
                        ],
                        max_length=30,
                        verbose_name="Type d'établissement",
                    ),
                ),
                ("address", models.TextField(verbose_name="Adresse complète")),
                ("latitude", models.FloatField(verbose_name="Latitude")),
                ("longitude", models.FloatField(verbose_name="Longitude")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "opening_hours",
                    models.TextField(
                        blank=True,
                        help_text="Ex: Lun-Ven: 8h-18h, Sam: 8h-12h",
                        null=True,
                        verbose_name="Horaires d'ouverture",
                    ),
                ),
                (
                    "has_emergency",
                    models.BooleanField(
                        default=False, verbose_name="Service d'urgence"
                    ),
                ),
                (
                    "has_pneumology",
                    models.BooleanField(
                        default=False, verbose_name="Service de pneumologie"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Établissement actif"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Établissement de santé",
                "verbose_name_plural": "Établissements de santé",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["facility_type", "is_active"],
                        name="community_h_facilit_c024ea_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="community_h_latitud_c8d5ac_idx",
                    ),
                ],
            },
        ),
    ]
