# Generated by Django 6.0 on 2026-01-15 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0006_zone_latitude_zone_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Faible'), ('MODERATE', 'Modéré'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='LOW', max_length=20, verbose_name='Niveau de risque')),
                ('pollution_level', models.FloatField(default=0.0, help_text='Niveau de pollution moyen (IQA)', verbose_name='Niveau de pollution')),
                ('respiratory_signal_count', models.IntegerField(default=0, help_text='Nombre de signaux respiratoires détectés dans cette zone', verbose_name='Nombre de signaux respiratoires')),
                ('high_risk_predictions_count', models.IntegerField(default=0, help_text='Nombre de prédictions à risque élevé dans cette zone', verbose_name='Prédictions à risque élevé')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Zone active')),
                ('radius_meters', models.FloatField(default=1000.0, help_text='Rayon de la zone en mètres (par défaut 1km)', verbose_name='Rayon (m)')),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_zone', to='sensors.zone', verbose_name='Zone géographique')),
            ],
            options={
                'verbose_name': 'Zone à risque',
                'verbose_name_plural': 'Zones à risque',
                'ordering': ['-risk_level', '-last_updated'],
                'indexes': [models.Index(fields=['risk_level', 'is_active'], name='community_r_risk_le_c4ac75_idx'), models.Index(fields=['last_updated'], name='community_r_last_up_5b9ebb_idx')],
            },
        ),
    ]
