# Generated by Django 6.0 on 2026-02-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0001_initial"),
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskzone",
            name="zone",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risk_zone",
                to="sensors.zone",
                verbose_name="Zone géographique",
            ),
        ),
        migrations.AddIndex(
            model_name="riskzone",
            index=models.Index(
                fields=["risk_level", "is_active"],
                name="community_r_risk_le_c4ac75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskzone",
            index=models.Index(
                fields=["last_updated"], name="community_r_last_up_5b9ebb_idx"
            ),
        ),
    ]
