# Generated by Django 6.0 on 2026-02-27 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comorbidity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ASTHMA", "Asthme"),
                            ("DIABETES", "Diabète"),
                            ("DEPRESSION", "Dépression"),
                            ("HEART_DISEASE", "Maladie cardiaque"),
                            (
                                "COPD",
                                "BPCO (Bronchopneumopathie chronique obstructive)",
                            ),
                            ("KIDNEY_DISEASE", "Maladie rénale"),
                            ("LIVER_DISEASE", "Maladie hépatique"),
                            ("CANCER", "Cancer"),
                            ("IMMUNOSUPPRESSION", "Immunosuppression"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=50,
                        verbose_name="Type de comorbidité",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("MILD", "Légère"),
                            ("MODERATE", "Modérée"),
                            ("SEVERE", "Sévère"),
                        ],
                        default="MILD",
                        max_length=20,
                        verbose_name="Sévérité",
                    ),
                ),
                (
                    "diagnosed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de diagnostic"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Comorbidité",
                "verbose_name_plural": "Comorbidités",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VaccinationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaccine_type",
                    models.CharField(
                        choices=[
                            ("PNEUMONIA", "Vaccin pneumonie (Pneumovax, Prevenar)"),
                            ("COVID19", "Vaccin COVID-19"),
                            ("FLU", "Vaccin grippe"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de vaccin",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OK", "OK"), ("EN_RETARD", "EN RETARD")],
                        default="OK",
                        max_length=20,
                        verbose_name="Statut vaccinal",
                    ),
                ),
                (
                    "is_vaccinated",
                    models.BooleanField(default=False, verbose_name="Vacciné"),
                ),
                (
                    "vaccination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de vaccination"
                    ),
                ),
                (
                    "booster_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de rappel"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Statut vaccinal",
                "verbose_name_plural": "Statuts vaccinaux",
                "ordering": ["vaccine_type"],
            },
        ),
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ],
                        verbose_name="Âge",
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True,
                        help_text="Taille en cm",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Taille (cm)",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True,
                        help_text="Poids en kg",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Poids (kg)",
                    ),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True,
                        help_text="Historique médical général",
                        null=True,
                        verbose_name="Historique médical",
                    ),
                ),
                (
                    "smoking_status",
                    models.CharField(
                        choices=[
                            ("NEVER", "Jamais"),
                            ("FORMER", "Ancien fumeur"),
                            ("CURRENT", "Fumeur actuel"),
                        ],
                        default="NEVER",
                        max_length=20,
                        verbose_name="Statut tabagique",
                    ),
                ),
                (
                    "alcohol_consumption",
                    models.CharField(
                        choices=[
                            ("NONE", "Aucune"),
                            ("OCCASIONAL", "Occasionnelle"),
                            ("REGULAR", "Régulière"),
                            ("HEAVY", "Importante"),
                        ],
                        default="NONE",
                        max_length=20,
                        verbose_name="Consommation d'alcool",
                    ),
                ),
                (
                    "vulnerability_index",
                    models.FloatField(
                        blank=True,
                        help_text="Score de vulnérabilité calculé (0-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Indice de vulnérabilité",
                    ),
                ),
                (
                    "vulnerability_index_last_calculated",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernier calcul de l'indice"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "comorbidities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="health_profiles",
                        to="health_profiles.comorbidity",
                        verbose_name="Comorbidités",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil de santé",
                "verbose_name_plural": "Profils de santé",
                "ordering": ["-created_at"],
            },
        ),
    ]
