# Generated by Django 6.0 on 2026-02-27 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("health_profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="healthprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="healthprofile",
            name="vaccination_statuses",
            field=models.ManyToManyField(
                blank=True,
                related_name="health_profiles",
                to="health_profiles.vaccinationstatus",
                verbose_name="Statuts vaccinaux",
            ),
        ),
    ]
