# Generated by Django 6.0 on 2026-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comorbidity',
            name='name',
            field=models.CharField(choices=[('ASTHMA', 'Asthme'), ('DIABETES', 'Diabète'), ('DEPRESSION', 'Dépression'), ('HEART_DISEASE', 'Maladie cardiaque'), ('COPD', 'BPCO (Bronchopneumopathie chronique obstructive)'), ('KIDNEY_DISEASE', 'Maladie rénale'), ('LIVER_DISEASE', 'Maladie hépatique'), ('CANCER', 'Cancer'), ('IMMUNOSUPPRESSION', 'Immunosuppression'), ('OTHER', 'Autre')], max_length=50, verbose_name='Type de comorbidité'),
        ),
    ]
