# Generated by Django 6.0 on 2026-01-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_profiles', '0002_add_depression_comorbidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationstatus',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('EN_RETARD', 'EN RETARD')], default='OK', max_length=20, verbose_name='Statut vaccinal'),
        ),
    ]
