# Generated by Django 6.0 on 2025-12-24 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="PatientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("smoking", models.BooleanField(default=False)),
                ("diabetes", models.BooleanField(default=False)),
                ("copd_asthma", models.BooleanField(default=False)),
                ("immunosuppression", models.BooleanField(default=False)),
                ("temperature", models.FloatField()),
                ("respiratory_rate", models.FloatField()),
                ("heart_rate", models.FloatField()),
                ("spo2", models.FloatField()),
                ("systolic_bp", models.FloatField()),
                ("wbc", models.FloatField()),
                ("curb65", models.IntegerField()),
                ("delta_respiratory_rate", models.FloatField()),
                ("delta_spo2", models.FloatField()),
                ("delta_wbc", models.FloatField()),
                ("rr_trend", models.FloatField()),
                ("spo2_trend", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_data",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Données patient",
                "verbose_name_plural": "Données patients",
                "ordering": ["-created_at"],
            },
        ),
    ]
