# Generated by Django 6.0 on 2025-12-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_created_at_alter_user_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientdata",
            options={
                "verbose_name": "Données patient",
                "verbose_name_plural": "Données patients",
            },
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="curb65",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="delta_respiratory_rate",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="delta_spo2",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="delta_wbc",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="heart_rate",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="respiratory_rate",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="rr_trend",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="spo2",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="spo2_trend",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="systolic_bp",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="temperature",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="wbc",
        ),
    ]
