# Generated by Django 6.0 on 2026-01-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_patientdata_options_remove_patientdata_curb65_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdata",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nom du contact d'urgence",
            ),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Téléphone du contact d'urgence",
            ),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="emergency_contact_relation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FATHER", "Père"),
                    ("MOTHER", "Mère"),
                    ("SPOUSE", "Époux / Épouse"),
                    ("DOCTOR", "Médecin"),
                    ("BROTHER", "Frère"),
                    ("SISTER", "Sœur"),
                    ("OTHER", "Autre"),
                ],
                max_length=20,
                null=True,
                verbose_name="Lien avec le contact d'urgence",
            ),
        ),
    ]
