# Generated by Django 6.0 on 2026-01-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_patientdata_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientdata",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="emergency_contact_phone",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="emergency_contact_relation",
        ),
    ]
