# Generated by Django 6.0 on 2026-01-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_patientdata_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdata",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="emergency_contact_relation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FATHER", "Père"),
                    ("MOTHER", "Mère"),
                    ("SPOUSE", "Époux / Épouse"),
                    ("BROTHER", "Frère"),
                    ("SISTER", "Sœur"),
                    ("OTHER", "Autre"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
