# Generated by Django 6.0 on 2025-12-24 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.JSONField()),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prédiction",
                "verbose_name_plural": "Prédictions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SensorMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("respiratory_rate", models.FloatField()),
                ("heart_rate", models.FloatField()),
                ("spo2", models.FloatField()),
                ("systolic_bp", models.FloatField()),
                ("wbc", models.FloatField()),
                ("curb65", models.IntegerField(default=0)),
                ("delta_respiratory_rate", models.FloatField(default=0.0)),
                ("delta_spo2", models.FloatField(default=0.0)),
                ("delta_wbc", models.FloatField(default=0.0)),
                ("rr_trend", models.FloatField(default=0.0)),
                ("spo2_trend", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_measurements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesure capteur",
                "verbose_name_plural": "Mesures capteurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
