# Generated by Django 6.0 on 2026-02-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.JSONField()),
                ("result", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prédiction",
                "verbose_name_plural": "Prédictions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SensorMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("respiratory_rate", models.FloatField()),
                ("heart_rate", models.FloatField()),
                ("spo2", models.FloatField()),
                ("systolic_bp", models.FloatField()),
                ("wbc", models.FloatField()),
                ("curb65", models.IntegerField(default=0)),
                ("delta_respiratory_rate", models.FloatField(default=0.0)),
                ("delta_spo2", models.FloatField(default=0.0)),
                ("delta_wbc", models.FloatField(default=0.0)),
                ("rr_trend", models.FloatField(default=0.0)),
                ("spo2_trend", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mesure capteur",
                "verbose_name_plural": "Mesures capteurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirQualityMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pm25", models.FloatField()),
                ("pm10", models.FloatField()),
                ("o3", models.FloatField()),
                ("no2", models.FloatField()),
                ("so2", models.FloatField()),
                ("co", models.FloatField()),
                ("humidity", models.FloatField()),
                ("temperature", models.FloatField()),
                ("iqa", models.FloatField()),
                ("category", models.CharField(max_length=100)),
                ("advice", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="measurements",
                        to="alerts.alert",
                    ),
                ),
            ],
        ),
    ]
