# Generated by Django 6.0 on 2026-02-27 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sensors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prediction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="airqualitymeasurement",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="sensors.sensor",
            ),
        ),
        migrations.AddField(
            model_name="sensormeasurement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_measurements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Patient",
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sensors.zone"
            ),
        ),
    ]
