# Generated by Django 6.0 on 2026-01-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_environmentalmeasurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentalmeasurement",
            name="location_lat",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="environmentalmeasurement",
            name="location_lon",
            field=models.FloatField(),
        ),
    ]
