# Generated by Django 6.0 on 2026-01-10 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_rename_started_at_alert_phase_1_started_at_and_more"),
        ("sensors", "0004_alter_environmentalmeasurement_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AirQualityMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pm25", models.FloatField()),
                ("pm10", models.FloatField()),
                ("o3", models.FloatField()),
                ("no2", models.FloatField()),
                ("so2", models.FloatField()),
                ("co", models.FloatField()),
                ("humidity", models.FloatField()),
                ("temperature", models.FloatField()),
                ("iqa", models.FloatField()),
                ("category", models.CharField(max_length=100)),
                ("advice", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="measurements",
                        to="alerts.alert",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="sensors.sensor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sensor",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sensors.zone"
            ),
        ),
        migrations.DeleteModel(
            name="EnvironmentalMeasurement",
        ),
    ]
