# Generated by Django 6.0 on 2026-01-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_sensor_zone_airqualitymeasurement_sensor_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='zone',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
