# Generated by Django 6.0 on 2026-01-14 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "__first__"),
        ("sensors", "0005_sensor_zone_airqualitymeasurement_sensor_zone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensors",
                to="community.zone",
            ),
        ),
        migrations.DeleteModel(
            name="Zone",
        ),
    ]
